#!/usr/bin/env python3
"""Generate MODE 7 templates and compressed data for BBC config-nio."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

WIDTH = 40
HEIGHT = 25
BBC_DIR = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = BBC_DIR / "assets" / "config-nio-templates"
SRC_BBC_DIR = Path(__file__).resolve().parents[2] / "apps" / "config-nio" / "platform" / "bbc"
DEFAULT_LAYOUT = BBC_DIR / "config_nio_layout.json"


def load_layout(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        layout = json.load(f)
    screen = layout["screen"]
    if screen["width"] != WIDTH or screen["height"] != HEIGHT:
        raise ValueError(f"{path}: only {WIDTH}x{HEIGHT} MODE 7 layouts are supported")
    return layout


def find_best_seq(data: bytes, dst: int, max_offset: int = 256, max_seq_len: int = 129) -> tuple[int, int]:
    best_from = 0
    best = 0
    for src in range(max(dst - max_offset, 0), dst):
        limit = min(len(data) - dst, max_seq_len)
        for num in range(limit):
            if data[src + num] != data[dst + num]:
                break
            matched = num + 1
            if matched > best:
                best_from = src
                best = matched
    return best_from, best


def compress(data: bytes) -> bytes:
    out = bytearray()
    dst = 0
    raw_copy_len = 0
    raw_len_addr = 0
    while dst < len(data):
        src, best = find_best_seq(data, dst)
        if best >= 2 + (1 if raw_copy_len else 0):
            if raw_copy_len:
                out[raw_len_addr] = raw_copy_len
                raw_copy_len = 0
            out.append((best - 2) | 0x80)
            out.append((src - dst + 0x100) & 0xFF)
            dst += best
        else:
            if raw_copy_len == 127:
                out[raw_len_addr] = raw_copy_len
                raw_copy_len = 0
            if not raw_copy_len:
                raw_len_addr = len(out)
                out.append(0)
            out.append(data[dst])
            raw_copy_len += 1
            dst += 1
    if raw_copy_len:
        out[raw_len_addr] = raw_copy_len
    out.append(0)
    return bytes(out)


def macro_name(*parts: str) -> str:
    return "CONFIG_NIO_BBC_" + "_".join(parts).upper()


def write_layout_header(layout: dict) -> None:
    out = SRC_BBC_DIR / "config_nio_layout.h"
    lines = [
        "/* Generated by bbc/scripts/generate_config_nio_templates.py */",
        "#ifndef CONFIG_NIO_BBC_LAYOUT_H",
        "#define CONFIG_NIO_BBC_LAYOUT_H",
        "",
    ]

    def emit(prefix: tuple[str, ...], value) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                emit((*prefix, key), child)
        elif isinstance(value, int):
            lines.append(f"#define {macro_name(*prefix)} {value}")

    emit((), layout)
    lines.extend([
        "",
        "#endif",
        "",
    ])
    out.write_text("\n".join(lines), encoding="utf-8")


def write_template_data(assets: dict[str, bytes]) -> None:
    out = SRC_BBC_DIR / "config_nio_template_data.s"
    labels = {
        "CNHOSTS": "_config_nio_tpl_hosts",
        "CNBROW": "_config_nio_tpl_browse",
        "CNSLOTS": "_config_nio_tpl_slots",
    }
    lines = [
        "; Generated by bbc/scripts/generate_config_nio_templates.py",
        "        .export _config_nio_tpl_hosts",
        "        .export _config_nio_tpl_browse",
        "        .export _config_nio_tpl_slots",
        "",
        "        .rodata",
    ]
    for name, data in assets.items():
        packed = compress(data)
        lines.append("")
        lines.append(f"{labels[name]}:")
        for offset in range(0, len(packed), 16):
            chunk = ", ".join(f"${byte:02X}" for byte in packed[offset : offset + 16])
            lines.append(f"        .byte {chunk}")
    out.write_text("\n".join(lines) + "\n")


def read_template(path: Path, name: str) -> bytes:
    data = path.read_bytes()
    if len(data) != WIDTH * HEIGHT:
        raise ValueError(f"{path}: {name} input must be exactly {WIDTH * HEIGHT} bytes, got {len(data)}")
    return data


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", type=Path, default=DEFAULT_LAYOUT,
                        help="JSON layout source for dynamic overlay coordinates")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    layout = load_layout(args.layout)
    assets = {
        "CNHOSTS": read_template(TEMPLATE_DIR / "CNHOSTS", "CNHOSTS"),
        "CNBROW": read_template(TEMPLATE_DIR / "CNBROW", "CNBROW"),
        "CNSLOTS": read_template(TEMPLATE_DIR / "CNSLOTS", "CNSLOTS"),
    }
    write_template_data(assets)
    write_layout_header(layout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
